server:
  address: 0.0.0.0
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
